### ISSUE TITLE
.gitignore 建議的補充

### ISSUE THREAD

**Issue by lin826** [104corp/guideline#16]
舉手發問個，請問 [.gitignore 建議](https://github.com/104corp/guideline/blob/master/source-repository/operation.md#gitignore-%E5%BB%BA%E8%AD%B0) ，如果並非 NetBeans/IntelliJ/Eclipse 的使用者，會推薦使用 [gitignore.io](https://www.gitignore.io/) 來產生模板嗎？

**Comment by MilesChou** [comment]
模板畢竟只是個鷹架，所以還是對產生出來的內容改改改，然後會發現每次改出來的東西都有 87% 像。而 [.gitignore 建議](https://github.com/104corp/guideline/blob/master/source-repository/operation.md#gitignore-%E5%BB%BA%E8%AD%B0)就是這 87% 的內容。

至於要不要用模版產生器，我個人的話，對新語言、新框架、新的開發環境不熟悉，才會使用產生器參考與確認這些真的是要 ignore 的檔案；相對已知的環境會使用自己建立共用的模板（指上述的 87%）。

**Comment by minchao** [comment]
這裡的 `.gitignore 建議`，我的理解是，將常見的暫存檔案與開發者們使用的 IDE 的設定檔都列入設定。

關於提問的 `.gitignore` 檔案產生工具，我認為 gitignore.io 與 [github/gitignore](https://github.com/github/gitignore) 都是很好的模板參考來源。

**Comment by MilesChou** [comment]
感謝 @minchao 補充，這個建議確實是針對公司的開發環境而產生的。
