### ISSUE TITLE
公司統一命名規則，檔案命名問題

### ISSUE THREAD

**Issue by lllllinli** [104corp/guideline#9]
***問題：***

檔案命名的部分，要想一下
我們公司的縮寫是  104 Corp.
通常我們會需要建 namespace ，但是，通常變數開頭無法用數字
所以我都是用 Corp104 workaround  
@MilesChou 

是否以， ```Corp104``` ，作為公司命名變數

**Comment by MilesChou** [comment]
事實上，我也是用 `Corp104` 作為命名空間

**Comment by lllllinli** [comment]
就這麼決定吧
